server:
  port: 8008

mybatis-plus:
  mapper-locations: classpath:com/marlowe/staservice/mapper/xml/*.xml

spring:
  application:
    name: service-statistics

  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://49.234.17.206:3306/tcdb?serverTimezone=GMT%2B8
    username: admin
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


