server:
  port: 8001

mybatis-plus:
  mapper-locations: classpath:com/marlowe/eduservice/mapper/xml/*.xml
#  configuration:
  #    map-underscore-to-camel-case: true
  # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


spring:
  datasource:
    url: jdbc:mysql://49.234.17.206:3306/tcdb?serverTimezone=GMT%2B8
    username: admin
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver




  # 返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


#logging:
#  level:
#    root: INFO