server:
  port: 8001

mybatis-plus:
  mapper-locations: classpath:com/marlowe/eduservice/mapper/xml/*.xml
  #  configuration:
  #    map-underscore-to-camel-case: true
  # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


spring:
  datasource:
    url: jdbc:mysql://49.234.17.206:3306/tcdb?serverTimezone=GMT%2B8
    username: admin
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

# 开启熔断机制
feign:
  hystrix:
    enabled: true

# 设置hystrix超时时间，默认1000ms
hystrix:
  commond:
    default:
      execution:
        isolation:
          timeoutInMilliseconds: 6000