server:
  port: 8002

spring:
  application:
    name: service-oss
  profiles:
    active: dev
  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

aliyun:
  oss:
    file:
      endpoint: # your endpoint
      keyid: # your keyid
      keysecret: # your keysecret
      bucketname: # your bucketname
